### ISSUE TITLE
git is marked as optional but is actually a requirement

### ISSUE THREAD

**Issue by dennis-learningpool** [chucklorenz/demo-wiki#1]
https://github.com/chucklorenz/demo-wiki/wiki#1-install-prerequisites 

git is in the optional section, but is currently a requirement (although we intend to change that).

**Comment by dennis-learningpool** [comment]
to clarify: git is used within the tool itself to fetch the framework from github - we can (and should) be downloading and unpacking this using the archived zips, but that is currently a TODO.

**Comment by chucklorenz** [comment]
@dennis-learningpool ,
What I'm understanding you to say is that installation will fail during "node install" ("The Adapt framework was not found. It will be installed.") if git is not installed. Can you confirm that it is simply the local installation of git that is needed; no need for a GitHub acct, right?

**Comment by chucklorenz** [comment]
@dennis-learningpool 
When it's convenient, can you give me your opinion on these git-related fixes:
https://github.com/chucklorenz/demo-wiki/wiki#install-git
https://github.com/chucklorenz/demo-wiki/wiki#2-clone-the-adapt_authoring-project
thnx

**Comment by dennis-learningpool** [comment]
Hi @chucklorenz - just a quick note to confirm that you don't need the Github account, since the https uri is used to fetch the framework.

Sorry to leave you hanging there!

The fixes above look good, although in the second section, the command you provide will not create the folder "adapt_authoring-develop" as stated, but should just create the folder "adapt_authoring", I believe.

Thanks!
